spring:
  application:
    name: demo-test
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
server:
  port: 58888
  servlet:
    context-path: /demo/test

